//! Bridge between ProxyAuth's configuration and the `zerocrypt` vault.
//!
//! Everything cryptographic about a token — key derivation, sealing, the
//! signature, the optional obfuscation pass — now lives in the library.
//! What stays here is the mapping from `AppConfig` plus the build
//! constants onto a `Vault`, done once at startup.
//!
//! The vault is immutable after construction and `Send + Sync`, so a
//! single instance is shared by every worker with no lock and no cache
//! on the request path.

use std::sync::OnceLock;

use zerocrypt::{BuildKey, Factor, Vault};

use crate::build::build_info::get;
use crate::config::config::AppConfig;
use crate::token::security::{
    get_build_epochdate, get_build_hk, get_build_rand, get_build_seed2, get_build_time,
};

static VAULT: OnceLock<Vault> = OnceLock::new();

/// Domain string for the build key derivation.
///
/// Separates ProxyAuth's keys from those of anything else using the same
/// library: two callers feeding in identical material still get
/// unrelated keys.
const KEY_CONTEXT: &str = "proxyauth.token.v1";

/// Folds every build constant into the 32-byte key the vault uses as its
/// HKDF salt.
///
/// `build_hk` is the one carrying the entropy: 32 bytes from the OS
/// CSPRNG, generated by `build.rs` and transported by the keystore. It is
/// validated first, through `BuildKey::from_hex`, so a keystore exported
/// before the 256-bit change is refused rather than silently adopted.
///
/// The rest — build time, build random, build epoch, the field ordering —
/// add no entropy worth counting: a timestamp is guessable and the others
/// are small. What they add is a *binding*. Any difference in a binary's
/// build constants yields a different key, so two deployments that have
/// not deliberately synchronised through the keystore cannot accept each
/// other's tokens by accident. That is the property `shuffled_order` used
/// to provide when it was mixed into the old signature; folding it in
/// here keeps it, in the one place it can still matter.
///
/// Parts are length-prefixed inside `BuildKey::derive`, so no
/// rearrangement of them collides with another.
fn build_key() -> Result<BuildKey, String> {
    let hk =
        BuildKey::from_hex(&get_build_hk()).map_err(|e| format!("invalid build secret: {e}"))?;

    let ordering = get().shuffled_order_list().join(",");

    Ok(BuildKey::derive(
        KEY_CONTEXT,
        &[
            env!("CARGO_PKG_VERSION").as_bytes(),
            hk.as_bytes(),
            &get_build_time().to_le_bytes(),
            &get_build_rand().to_le_bytes(),
            &get_build_epochdate().to_le_bytes(),
            ordering.as_bytes(),
        ],
    ))
}

/// Builds the process-wide vault from the operator secret and the build
/// constants.
///
/// Call once, at startup, before any request is served — the same place
/// the derived key used to be initialised. Calling it again is a no-op,
/// so a second call cannot silently swap the key out from under
/// in-flight requests.
pub fn init(config: &AppConfig) -> Result<(), String> {
    let mut builder = Vault::builder(&config.secret)
        .key(build_key()?)
        .ttl(config.token_expiry_seconds.max(0) as u64);

    // `fast: true` skips the obfuscation pass; `fast: false` (the
    // default) applies it, keyed by BUILD_SEED2. Same meaning the flag
    // has always had, read once here instead of on every request.
    if !config.fast {
        let seed = get_build_seed2();
        let factor = u8::try_from(seed)
            .ok()
            .and_then(|v| Factor::new(v).ok())
            .ok_or_else(|| format!("BUILD_SEED2 ({seed}) is outside the accepted range 10..=99"))?;
        builder = builder.factor(factor);
    }

    // A second call is deliberately not an error: `init` is idempotent so
    // a test harness or a reload path can call it defensively.
    let _ = VAULT.set(builder.build());
    Ok(())
}

/// The process-wide vault.
///
/// # Panics
///
/// If [`init`] has not run. That is a startup-ordering bug, not a
/// runtime condition — failing loudly at the first request beats serving
/// traffic with a vault nobody configured.
pub fn vault() -> &'static Vault {
    VAULT
        .get()
        .expect("token vault used before init(); call token::vault::init at startup")
}
